language: php
php:
  - 7.2

services:
  - mysql

env:
  - DB_USER=root
  - DB_PASS=root

before_script:
  - composer selfupdate
  - composer install
  - mysql -u $DB_USER -p $DB_PASS < tests/database.sql

script:
  - ./vendor/bin/phpunit --colors
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpcbf